# Generated by Django 5.1.4 on 2025-02-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriangle_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEORequest',
        ),
    ]
