# Generated by Django 5.1.4 on 2025-03-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriangle_app', '0004_alter_seoresult_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
